name: islamforever
description: "Dawat-e-Islam project by Awais Mansha"
publish_to: "none"
version: 1.0.2+7

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  flutter_styled_toast: ^2.2.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  loading_animation_widget: ^1.2.1
  android_id: ^0.3.5
  device_info_plus: ^10.1.2
  photo_view: ^0.15.0
  shared_preferences: ^2.2.3
  flutter_image_compress: ^2.3.0
  fluttertoast: ^8.2.6
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  firebase_core: ^3.8.0
  flutter_native_splash: ^2.3.13
  flutter_dotenv: ^5.0.2
  dio: ^5.4.1
  uuid: ^4.4.0
  provider: ^6.0.5
  shimmer: ^3.0.0
  simple_gradient_text: ^1.3.0
  gradient_elevated_button: ^1.0.0
  modal_bottom_sheet: ^3.0.0
  webview_flutter: ^4.4.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.0
  share_plus: ^10.0.0
  text_scroll: ^0.2.0
  carousel_slider: ^5.0.0
  avatar_glow: ^3.0.1
  font_awesome_flutter: ^10.8.0
  html: ^0.15.5
  flutter_rating_bar: ^4.0.1
  youtube_player_flutter: ^9.1.1
  vimeo_video_player: ^1.0.1
  flutter_inappwebview: ^6.1.5
  video_player: ^2.9.2
  chewie: ^1.9.2
  onesignal_flutter: ^5.2.7
  cached_network_image: ^3.4.1
  just_audio: ^0.9.43
  rxdart: ^0.28.0
  flutter_widget_from_html: ^0.15.3
  connectivity_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_islamforever_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter_native_splash:
  android: true
  ios: true
  web: false

  image: "assets/images/ic_islamforever_icon.png"
  color: "#2eb98e"

  android_12:
    image: "assets/images/ic_islamforever_icon_android12.png"
    color: "#2eb98e"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - .env
    - assets/translations/
    - assets/music/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900
